In [1]:
import numpy as np

In [25]:
# creating Array by using list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# Creating Arrays using In-built Methods

### Total 6 Methods

- 1. zeros
- 2. ones
- 3. full → for using your own value
- 4. eye → for identity matrix
- 5. arange
- 6. linspace → for evenly spaced matrix creation

In [24]:
# creating auto fill array of zeros and ones
arr0 = np.zeros((2,3) , dtype = "int64")
print(arr0)
print(arr0.shape ,"\n")

# for prefilled with ones 1:
arr1 = np.ones((2,3) , dtype = "int64")
print(arr1)
print(arr1.shape , "\n")

# for prefilling woith the value you want:
arr3 = np.full((2,4), 99 , dtype = "int64")
print(arr3)
print(arr3.shape , "\n")

# for creating an identitiy matrix:
arr4 = np.eye((3) , dtype = "int64")
print(arr4)
print(arr4.shape , "\n")

# for an range matrix :
arr5 = np.arange(1 , 12 , 2 , dtype = "int64")
print(arr5)
print(arr5.shape , "\n")

# for an linespace or evenly space matrix :
arr6 = np.linspace( 1,100, 4 , dtype = "int64")
print(arr6)
print(arr6.shape , "\n")

[[0 0 0]
 [0 0 0]]
(2, 3) 

[[1 1 1]
 [1 1 1]]
(2, 3) 

[[99 99 99 99]
 [99 99 99 99]]
(2, 4) 

[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3) 

[ 1  3  5  7  9 11]
(6,) 

[  1  34  67 100]
(4,) 



# Properties

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) # for dimensions
print(arr.size)  # for total elements
print(arr.dtype) # for data type
print(arr.ndim) # for number of dimension 1,2,3D
# for --- "typecasting"--- means changing datatype
float_arr = arr.astype(np.float64)
print(float_arr ,"\n", float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 
 float64


# Operations on Array:

In [39]:
arr = np.array([[1,2,3] , [3,4,5]])
print("Original shape is: ",arr.shape)

reshaped_arr = arr.reshape(3,2)
print(reshaped_arr ,"\nThe shape is changed to :", reshaped_arr.shape)

# for flattened Array :(means changing from 2D to 1D)
flattened_arr = arr.flatten()
print(f"The flattened array is : {flattened_arr} \nThe shape of the array is : {flattened_arr.shape}")

Original shape is:  (2, 3)
[[1 2]
 [3 3]
 [4 5]] 
The shape is changed to : (3, 2)
The flattened array is : [1 2 3 3 4 5] 
The shape of the array is : (6,)


In [41]:
arr = np.array([1,2,3,4,5])

# Fancy indexing :
idx = [1,3,4]
print(arr[idx])

# Boolean indexing :
print(arr[arr > 3]) #condition bhi laga skte hn koi jo chaiye oske liye


[2 4 5]
[4 5]


# 3d array and multi-dimention array:


In [56]:
arr3d = np.array([[[1,2],[3,9],[4,6]],[[7,8],[5,11],[10,12]]])
print(arr3d)

# indexing
print(arr3d[0,1,1])

# silicing
print(arr3d[: , 0 , :])    #[firstly which array : rows : columns]
print(arr3d[: , : , 0])    # first column selected

# also we can change the selected values:
arr3d[: , 0 , :] = 99
print(arr3d)

[[[ 1  2]
  [ 3  9]
  [ 4  6]]

 [[ 7  8]
  [ 5 11]
  [10 12]]]
9
[[1 2]
 [7 8]]
[[ 1  3  4]
 [ 7  5 10]]
[[[99 99]
  [ 3  9]
  [ 4  6]]

 [[99 99]
  [ 5 11]
  [10 12]]]


## Broadcasting main thing is Vector Normalization:
- (array - mean) / std deviation (formula of standard normalization {z-score})

In [60]:
# normalizing 
arr = np.array([[1,2] , [3,4]])

arr_mean = arr.mean()
arr_std = arr.std()

print(f"The mean is : {arr_mean}")
print(f"The std deviation is : {arr_std}")

normalized = (arr - arr_mean) / arr_std   # formula 
print(f"The Normalized Array is:\n {normalized}" )

The mean is : 2.5
The std deviation is : 1.118033988749895
The Normalized Array is:
 [[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


# Mathematical Function (Aggregiate)

In [73]:
#----------------------AGGREGATE FUNCS-----------------
# Summarize data and typically return a single value

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])
print("for Aggregiate Funtions \n")
print(np.sum(array))
print(np.prod(array))
print(np.mean(array))
print(np.median(array))
print(np.std(array))    #standard deviation
print(np.var(array))    #vairance
print(np.min(array))
print(np.max(array))
print(np.argmin(array)) #index of min value "arg"
print(np.argmax(array)) #same

# ----VECTORIZED MATH FUNCTIONS -----(VECTOR IS SINGLE DIMENSION)
# OPERATIONS APPLY A FUNCTION TO AN ENTIRE ARRAY  
arr = np.array([1.01, 2.5, 3.99])
print("for Powers \n")
print(np.square(array))
print(np.pow(array, 3))  # for having power--- pow(a,b)
print(np.sqrt(array))   #SQUARE ROOT

print("for roundoff \n")
print(np.round(arr))  #ROUND OF AN ARRAY 
print(np.floor(arr))    #ROUND-DOWN
print(np.ceil(arr))     #ROUND-UP
print(np.pi)
print(np.trunc(arr))  # for neglecting the values after point . 

print("For log\n")
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr)) # for exponent

print("Extra are: \n")
print(np.unique(array))  # if repeated numbers then use this -- works like a set 
print(np.sort(array))   # line wise in a flow
print(np.abs(arr))    # absolute values neglected neg sign 

# print(np.sum(array, axis = 0)) #Axis to perform operation with in a array row or columns 
# print(np.sum(array, axis = 1))#axis=0 se columns pr kaam hoga aur axis=1 se row k andr hi

for Aggregiate Funtions 

55
3628800
5.5
5.5
2.8722813232690143
8.25
1
10
0
9
for Powers 

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]
[[   1    8   27   64  125]
 [ 216  343  512  729 1000]]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
for roundoff 

[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793
[1. 2. 3.]
For log

[0.00995033 0.91629073 1.38379123]
[0.01435529 1.32192809 1.99638875]
[ 2.74560102 12.18249396 54.05488936]
Extra are: 

[ 1  2  3  4  5  6  7  8  9 10]
